/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_CMDSERVER_PB_H_INCLUDED
#define PB_CMDSERVER_PB_H_INCLUDED
#include <lib/pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _CmdRequest {
    int32_t id; /* request id */
    pb_callback_t fn; /* function name */
    pb_callback_t data;
} CmdRequest;

typedef struct _CmdResponse {
    int32_t id;
    pb_callback_t data;
} CmdResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define CmdRequest_init_default                  {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define CmdResponse_init_default                 {0, {{NULL}, NULL}}
#define CmdRequest_init_zero                     {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define CmdResponse_init_zero                    {0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define CmdRequest_id_tag                        1
#define CmdRequest_fn_tag                        2
#define CmdRequest_data_tag                      3
#define CmdResponse_id_tag                       1
#define CmdResponse_data_tag                     2

/* Struct field encoding specification for nanopb */
#define CmdRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    id,                1) \
X(a, CALLBACK, SINGULAR, STRING,   fn,                2) \
X(a, CALLBACK, SINGULAR, STRING,   data,              3)
#define CmdRequest_CALLBACK pb_default_field_callback
#define CmdRequest_DEFAULT NULL

#define CmdResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    id,                1) \
X(a, CALLBACK, SINGULAR, STRING,   data,              2)
#define CmdResponse_CALLBACK pb_default_field_callback
#define CmdResponse_DEFAULT NULL

extern const pb_msgdesc_t CmdRequest_msg;
extern const pb_msgdesc_t CmdResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define CmdRequest_fields &CmdRequest_msg
#define CmdResponse_fields &CmdResponse_msg

/* Maximum encoded size of messages (where known) */
/* CmdRequest_size depends on runtime parameters */
/* CmdResponse_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
